# brands
- for: 'brands.create'
  items:
    - title: 'Brand List'
      route: 'brands.index'
    - title: 'New Brand'
      route: null
- for: 'brands.create'
  items:
    - title: 'Brand List'
      route: 'brands.index'
    - title: 'Brand Detail'
      route: null
