/*==========================
      AWS ECS Service
===========================*/

resource "aws_ecs_service" "ecs_service" {
  name                              = var.name
  cluster                           = var.ecs_cluster_id
  task_definition                   = var.task_definition_arn
  desired_count                     = var.desired_count
  health_check_grace_period_seconds = 10
  launch_type                       = "FARGATE"
  enable_execute_command = var.enable_execute_command

  network_configuration {
    security_groups = [var.security_group_arn]
    subnets         = [var.subnet_ids[0], var.subnet_ids[1]]
  }

  load_balancer {
    target_group_arn = var.target_group_arn
    container_name   = var.container_name
    container_port   = var.container_port
  }

#   deployment_controller {
#     type = "CODE_DEPLOY"
#   }

  lifecycle {
    // to avoid changes generated by autoscaling or new CodeDeploy changes
    ignore_changes = [desired_count, task_definition, load_balancer]
  }
}
